/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e9ddff",
        "inverse-surface": "#322f35",
        "primary-fixed": "#e9ddff",
        "surface-container-highest": "#e6e0e9",
        "secondary": "#63597c",
        "inverse-on-surface": "#f5eff7",
        "surface-variant": "#e6e0e9",
        "on-primary-container": "#e0d2ff",
        "surface-bright": "#fdf7ff",
        "surface-container-low": "#f8f2fa",
        "on-surface": "#1d1b20",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#4b4263",
        "tertiary": "#765b00",
        "on-primary-fixed-variant": "#4f378a",
        "primary-container": "#6750a4",
        "on-tertiary-fixed-variant": "#594400",
        "surface-container": "#f2ecf4",
        "secondary-fixed-dim": "#cdc0e9",
        "on-tertiary-container": "#503d00",
        "surface-tint": "#6750a4",
        "tertiary-fixed": "#ffdf93",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#7a7582",
        "surface-dim": "#ded8e0",
        "secondary-container": "#e1d4fd",
        "inverse-primary": "#cfbcff",
        "on-primary-fixed": "#22005d",
        "on-background": "#1d1b20",
        "on-secondary-container": "#645a7d",
        "outline-variant": "#cbc4d2",
        "surface-container-high": "#ece6ee",
        "on-surface-variant": "#494551",
        "error": "#ba1a1a",
        "primary": "#4f378a",
        "on-secondary-fixed": "#1f1635",
        "background": "#fdf7ff",
        "tertiary-container": "#c9a74d",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#fdf7ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#241a00",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#cfbcff",
        "tertiary-fixed-dim": "#e7c365"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "auto",
        "max-width": "1200px",
        "stack-lg": "64px",
        "stack-sm": "12px",
        "gutter": "24px",
        "section-padding": "120px",
        "stack-md": "32px"
      },
      fontFamily: {
        "headline-md": ["Syne", "sans-serif"],
        "display-lg-mobile": ["Syne", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "body-main": ["DM Sans", "sans-serif"],
        "subhead-italic": ["EB Garamond", "serif"],
        "label-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg": ["80px", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-main": ["16px", { lineHeight: "1.7", letterSpacing: "0.01em", fontWeight: "400" }],
        "subhead-italic": ["24px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-mono": ["13px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
